// src/validation/taxonomy/static-provider.ts
// Deterministic ESCO skill taxonomy lookup — sub-millisecond, zero API calls.
// Loads a pre-built JSON file generated by scripts/build-taxonomy.ts.

import fs from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import type { ITaxonomyProvider, SkillEntry, TaxonomyData } from "./provider.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export class StaticTaxonomyProvider implements ITaxonomyProvider {
  private readonly synonymMap: Map<string, string>;
  private readonly skillMap: Map<string, SkillEntry>;

  constructor() {
    this.synonymMap = new Map();
    this.skillMap = new Map();

    try {
      const raw = fs.readFileSync(
        join(__dirname, "skills-taxonomy.json"),
        "utf8",
      );
      const data: TaxonomyData = JSON.parse(raw);

      for (const [uri, entry] of Object.entries(data.skills)) {
        this.skillMap.set(uri, entry);

        this.synonymMap.set(
          entry.preferredLabel.toLowerCase().trim(),
          uri,
        );

        for (const alt of entry.altLabels ?? []) {
          this.synonymMap.set(alt.toLowerCase().trim(), uri);
        }
      }

      console.log(
        `[taxonomy] Loaded ${this.synonymMap.size} synonyms across ${this.skillMap.size} skills`,
      );
    } catch (e) {
      console.warn(
        "[taxonomy] skills-taxonomy.json not found — taxonomy disabled. Run: npm run setup-taxonomy",
      );
    }
  }

  normalize(skill: string): string | null {
    return this.synonymMap.get(skill.toLowerCase().trim()) ?? null;
  }

  getSynonyms(uri: string): string[] {
    const entry = this.skillMap.get(uri);
    if (!entry) return [];
    return [entry.preferredLabel, ...(entry.altLabels ?? [])];
  }

  getCanonicalLabel(uri: string): string | null {
    return this.skillMap.get(uri)?.preferredLabel ?? null;
  }

  getBroader(uri: string): string[] {
    return this.skillMap.get(uri)?.broader ?? [];
  }

  getNarrower(uri: string): string[] {
    return this.skillMap.get(uri)?.narrower ?? [];
  }
}
