--
-- PostgreSQL database dump
--

\restrict WJn7XgLZkIaTlSMH5gIfIlnI7QXdqVGYAr46zY4D4Fu3XHG7iVc2hMUqGKGqysH

-- Dumped from database version 16.12
-- Dumped by pg_dump version 16.12

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    full_name character varying(255),
    password character varying(255),
    provider character varying(255) NOT NULL,
    provider_id character varying(255),
    CONSTRAINT auth_users_provider_check CHECK (((provider)::text = ANY ((ARRAY['LOCAL'::character varying, 'GOOGLE'::character varying, 'GITHUB'::character varying])::text[])))
);


ALTER TABLE public.auth_users OWNER TO postgres;

--
-- Name: auth_users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: job_applications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_applications (
    id bigint NOT NULL,
    applied_on timestamp(6) without time zone,
    company character varying(255),
    cover_letter_content text,
    generated_resume_content text,
    job_description text,
    job_id character varying(255),
    location character varying(255),
    outcome character varying(255),
    "position" character varying(255),
    user_id bigint,
    CONSTRAINT job_applications_outcome_check CHECK (((outcome)::text = ANY ((ARRAY['ACTIVE'::character varying, 'IN_PROCESS'::character varying, 'REJECTED'::character varying, 'OFFER_RECEIVED'::character varying, 'DRAFT'::character varying])::text[])))
);


ALTER TABLE public.job_applications OWNER TO postgres;

--
-- Name: job_applications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.job_applications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_applications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resume_bases; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.resume_bases (
    id bigint NOT NULL,
    content text NOT NULL,
    has_icons boolean NOT NULL,
    name character varying(255) NOT NULL,
    user_id bigint
);


ALTER TABLE public.resume_bases OWNER TO postgres;

--
-- Name: resume_bases_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.resume_bases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resume_bases_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_profile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_profile (
    id bigint NOT NULL,
    address character varying(255),
    email character varying(255),
    full_name character varying(255),
    github_url character varying(255),
    linkedin_url character varying(255),
    master_subjects text,
    masters_degree character varying(255),
    masters_gpa character varying(255),
    phone character varying(255),
    portfolio_url character varying(255),
    user_id bigint
);


ALTER TABLE public.user_profile OWNER TO postgres;

--
-- Name: user_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_users (id, created_at, email, full_name, password, provider, provider_id) FROM stdin;
1	2026-02-18 20:25:47.850784	saitejamukkera@gmail.com	Sai Teja	\N	GOOGLE	111228960066736357919
\.


--
-- Data for Name: job_applications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.job_applications (id, applied_on, company, cover_letter_content, generated_resume_content, job_description, job_id, location, outcome, "position", user_id) FROM stdin;
\.


--
-- Data for Name: resume_bases; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.resume_bases (id, content, has_icons, name, user_id) FROM stdin;
\.


--
-- Data for Name: user_profile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_profile (id, address, email, full_name, github_url, linkedin_url, master_subjects, masters_degree, masters_gpa, phone, portfolio_url, user_id) FROM stdin;
\.


--
-- Name: auth_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_users_id_seq', 1, true);


--
-- Name: job_applications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.job_applications_id_seq', 1, false);


--
-- Name: resume_bases_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.resume_bases_id_seq', 1, false);


--
-- Name: user_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_profile_id_seq', 1, false);


--
-- Name: auth_users auth_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_users
    ADD CONSTRAINT auth_users_pkey PRIMARY KEY (id);


--
-- Name: job_applications job_applications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_applications
    ADD CONSTRAINT job_applications_pkey PRIMARY KEY (id);


--
-- Name: resume_bases resume_bases_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.resume_bases
    ADD CONSTRAINT resume_bases_pkey PRIMARY KEY (id);


--
-- Name: resume_bases uk1l7onpdc8jqbswae9s3n13l21; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.resume_bases
    ADD CONSTRAINT uk1l7onpdc8jqbswae9s3n13l21 UNIQUE (name);


--
-- Name: auth_users uk6jqfsuvys3lan090p4mk16a5t; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_users
    ADD CONSTRAINT uk6jqfsuvys3lan090p4mk16a5t UNIQUE (email);


--
-- Name: user_profile ukebc21hy5j7scdvcjt0jy6xxrv; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_profile
    ADD CONSTRAINT ukebc21hy5j7scdvcjt0jy6xxrv UNIQUE (user_id);


--
-- Name: user_profile user_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_profile
    ADD CONSTRAINT user_profile_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict WJn7XgLZkIaTlSMH5gIfIlnI7QXdqVGYAr46zY4D4Fu3XHG7iVc2hMUqGKGqysH

