ALTER TABLE job_applications
  ADD COLUMN IF NOT EXISTS ats_score INTEGER,
  ADD COLUMN IF NOT EXISTS impact_score INTEGER,
  ADD COLUMN IF NOT EXISTS score_version INTEGER DEFAULT 1,
  ADD COLUMN IF NOT EXISTS score_breakdown JSONB;
